PUT http://localhost:3000/api/users/4/instance HTTP/1.1
Content-Type: application/json

{
  "firstName":"Alex",
  "lastName":"Rob",
  "email":"mariii@gmail.com",
  "password":"123123",
  "birthday":"2003-12-18",
  "isMale":false
}